index:
    path: /
    controller: App\Controller\DefaultController::index

catalog_list:
    path: /catalog/{catalog}
    controller: App\Controller\DefaultController::catalogList

product_info:
    path: /catalog/{catalog}/{product}
    controller: App\Controller\DefaultController::productInfo